import Head from 'next/head'
import Link from 'next/link'
import { getLayout } from '@/src/widgets/Layout/Layout'
import { PasswordResetController } from '@/src/features/auth/PasswordResetController/PasswordResetController'

const ResetPasswordPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to Inctagram!</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
        <Link href={`/signup`} />
      </Head>
      <PasswordResetController />
    </>
  )
}

ResetPasswordPage.getLayout = getLayout

export default ResetPasswordPage
