import Head from 'next/head'
import Link from 'next/link'
import { ForgotPassword } from '@/src/widgets/ForgotPassword/ForgotPassword'
import { getLayout } from '@/src/widgets/Layout/Layout'

const ForgotPasswordPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to Inctagram!</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
        <Link href={`/signup`} />
      </Head>
      <ForgotPassword />
    </>
  )
}

ForgotPasswordPage.getLayout = getLayout

export default ForgotPasswordPage
