import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import { getLayoutWithSidebar } from '@/src/widgets/Layout/LayoutWithSidebar'
import { getLayout } from '@/src/widgets/Layout/Layout'

const inter = Inter({ subsets: ['latin'] })

const SignUp = () => {
  return (
    <div className={`h-[10000px] bg-gradient-to-b from-dark-100 to-dark-500 `}>
      <Head>
        <title>Welcome to Inctagram!</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
        <Link href={`/signup`} />
      </Head>
      <h1 style={{ textAlign: 'center' }}>Get logged id</h1>
    </div>
  )
}

// SignUp.getLayout = getLayout
SignUp.getLayout = getLayoutWithSidebar

export default SignUp
